import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import client from '../api/client';
import { Download, FileText, ArrowLeft, Building2, Sparkles } from 'lucide-react';

export const ReportView = () => {
  const { reportId } = useParams();
  const navigate = useNavigate();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    client.get(`/reports/${reportId}`)
      .then((res) => setReport(res.data))
      .catch((err) => console.error(err))
      .finally(() => setLoading(false));
  }, [reportId]);

  if (loading) return <div className="text-center py-12 text-xs text-slate-400">Loading AI report document...</div>;
  if (!report) return <div className="text-center py-12 text-xs text-slate-400">Report document not found.</div>;

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 space-y-6">
      
      <div className="flex justify-between items-center">
        <button
          onClick={() => navigate(-1)}
          className="inline-flex items-center space-x-1.5 text-xs font-bold text-slate-500 hover:text-slate-800 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back</span>
        </button>

        <a
          href={report.pdf_url}
          target="_blank"
          rel="noopener noreferrer"
          className="px-4 py-2 bg-[#1A7A6A] hover:bg-[#0F5548] text-white font-bold text-xs rounded-xl shadow-lg transition-all flex items-center space-x-2"
        >
          <Download className="w-4 h-4" />
          <span>Download Formal PDF Report</span>
        </a>
      </div>

      {/* Printable Report Document Card */}
      <div className="bg-white rounded-3xl p-8 sm:p-12 border border-slate-200 shadow-2xl space-y-6">
        
        {/* Department Header */}
        <div className="text-center pb-6 border-b-2 border-[#1A7A6A]">
          <div className="text-xl font-extrabold text-[#1F3864] uppercase tracking-wide">
            Union Christian College, Aluva
          </div>
          <div className="text-sm font-semibold text-[#1A7A6A] mt-0.5">
            (Autonomous) — School of Computer Applications
          </div>
          <div className="mt-3 inline-block px-4 py-1 bg-[#E8F5F2] text-[#0F5548] font-bold text-xs rounded-full">
            {report.report_type === 'annual' ? `ANNUAL REPORT ${report.year}` : 'FORMAL ACTIVITY REPORT'}
          </div>
        </div>

        {/* Report Metadata */}
        <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 text-xs space-y-1">
          <div>Generated By: <strong>{report.generated_by_name}</strong></div>
          <div>Generated Date: <strong>{new Date(report.generated_at).toLocaleDateString()}</strong></div>
          <div>Cloudinary PDF Link: <a href={report.pdf_url} target="_blank" rel="noreferrer" className="text-[#1A7A6A] underline">Open Document</a></div>
        </div>

        {/* Narrative Body */}
        <div className="prose max-w-none text-xs sm:text-sm text-slate-800 leading-relaxed whitespace-pre-line">
          {report.ai_narrative}
        </div>

        {/* Signatures */}
        <div className="pt-12 flex justify-between items-center text-xs text-slate-500">
          <div className="text-center">
            <div className="w-36 border-t border-slate-400 mb-1"></div>
            <div>Faculty Coordinator</div>
          </div>
          <div className="text-center">
            <div className="w-36 border-t border-slate-400 mb-1"></div>
            <div>Head of Department (SCA)</div>
          </div>
        </div>

      </div>
    </div>
  );
};
